### ISSUE TITLE
How long was training time and on what architecture?

### ISSUE THREAD

**Issue by DominiquePaul** [biomed-AI/TransEPI#2]
Hi,
I am thinking about retraining the model on slightly different data (one-hot encoding of DNA). This would require me to add an initial CNN layer. I am wondering how long this might take to train.

Could you specify how long it took you to train the initial model (time) as well as the number of epochs. Moreover, it would be great if you could mention the compute you were using (CPU or GPU and which kind of processor)

Thanks a lot!

best
Dominique

**Comment by chenkenbio** [comment]
Hello, the training process takes about 18min/epoch (5-fold CV) on a single 3090 GPU. We trained the model for 12 epochs (the best performance on validation data was achieved in the second epoch). You can refer to the [training log](https://github.com/biomed-AI/TransEPI/blob/main/dev/config_500bp_cv.log) for more details model training.

**Comment by DominiquePaul** [comment]
Hi,

Thanks for your swift response on the last question.

I am taking a closer look at your dataset class and specifically the `rand_shift`. I initially thought that this would introduce small random shifts in the loaded training data, similar as is done in the Enformer paper, but I don’t think that’s the case. I did not find any mention of it in the paper - maybe that’s just me though.

What exactly does rand_shift do?

Thanks a lot!

best
Dominique

—
Dominique Paul
Statistics master’s student | ETH Zurich
Mobile: +41 76 801 7796
Email: ***@***.******@***.***>
On 23. Oct 2022, 00:24 +0200, Ken Chen ***@***.***>, wrote:

Hello, the training process takes about 18min/epoch (5-fold CV) on a single 3090 GPU. We trained the model for 12 epochs (the best performance on validation data was achieved in the second epoch). You can refer to the training log<https://github.com/biomed-AI/TransEPI/blob/main/dev/config_500bp_cv.log> for more details model training.

**Comment by chenkenbio** [comment]
Hello,

The "rand_shfit" feature was introduced to help TransEPI to adapt to  the situations where enhancer-promoter pair reside near the ends of chromosomes. By default, the enhancers and promoters are symmetrically located in the 2.5Mbp regions and the both sides in the regions are almost equally informative. However, when the enhancers or the promoters reside close to the ends of chromosomes, the regions exceeding the range of chromosomes will be less informative because they will be filled with 0. Since the number of samples near the chromosome ends is usually small, we used the "rand_shift" operation to avoid that the features of samples near chromosome ends are too different from the others'.

The reason why I did not mention this feature in the paper is because I found that this feature has almost no effect on the results. You can just ignore this feature. (Or you may put it to `__getitem__` to make it work as a function for data augmentation)

**Comment by DominiquePaul** [comment]
Great, thanks a lot!

—
Dominique Paul
Mobile: +41 76 801 7796
***@***.***
